### ISSUE TITLE
tagged release.

### ISSUE THREAD

**Issue by maxice8** [bad-day/npyscreen#1]
I'm trying to package https://github.com/bad-day/TelegramTUI which depends on this library but i couldn't find any tagged release with source tarball to use.

**Comment by vtr0n** [comment]
I need to create a new release on this repo?

**Comment by maxice8** [comment]
yes

**Comment by vtr0n** [comment]
Done

**Comment by maxice8** [comment]
thanks, https://github.com/voidlinux/void-packages/pull/12853
